version: "3.8"

services :
  postgres:
    image: postgres:14
    container_name: backend-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: nest
    networks:
      - devNetwork

networks:
  devNetwork:

